
NDefines.NEconomy.EDICTS_COST_INCREASE = 2							-- % increase on state maintenance.
NDefines.NEconomy.EDICTS_DURATION_MONTHS = 12						-- months lastin at least.
NDefines.NEconomy.DEBASE_MAX_STORED_MONTHS = 0						-- Debase currency stores up to this many months of charges.
NDefines.NEconomy.DEBASE_MONTHS_PER_CHARGE = 30						-- Amount of months used for one debase charge.
NDefines.NEconomy.DEBASE_MAX_CORRUPTION = 90						-- Above this level of corruption, you won't be able to Debase Currency.
NDefines.NEconomy.DEBASE_ADDED_CORRUPTION = 10						-- This amount of corruption added per standard sized bank loan worth of currency.
NDefines.NEconomy.GOLD_MINE_SIZE = 30								-- Base income from gold mines
NDefines.NEconomy.GOLD_MINE_DEPLETION_THRESHOLD = 999				-- Gold mines above production level or above can be depleted
NDefines.NEconomy.GOLD_MINE_DEPLETION_CHANCE = 0					-- Chance of gold mine being depleted (yearly, per production above threshold)
NDefines.NEconomy.GOLD_MINE_SIZE_PRIMITIVES = 20					-- Gold income for very slow techgroups
NDefines.NEconomy.TRADE_POWER_HOME_BONUS = 0.05
NDefines.NEconomy.TRADE_POWER_HOME_BONUS_MAX = 0.1
NDefines.NEconomy.AUTONOMY_AT_DIPLO_ANNEX = 30						-- Autonomy added when diplo-annexing
NDefines.NEconomy.AUTONOMY_AT_CONQUEST = 70							-- Autonomy added at conquest
NDefines.NEconomy.AUTONOMY_AT_CONQUEST_CLAIM = 40					-- Autonomy added at conquest if you have a claim
NDefines.NEconomy.AUTONOMY_AT_CONQUEST_CORE = 10					-- Autonomy added at conquest if you have a core
NDefines.NEconomy.OVERSEAS_MIN_AUTONOMY = 35						-- Overseas provinces always have at least this much autonomy
NDefines.NEconomy.COLONY_MIN_AUTONOMY = 50							-- Colonial cores always have at least this much autonomy
NDefines.NEconomy.CAPITAL_MAX_AUTONOMY = 100						-- Capital province autonomy can never be above this
NDefines.NEconomy.DECREASE_AUTONOMY_STEP = -10
NDefines.NEconomy.DECREASE_AUTONOMY_MIN = 10
NDefines.NEconomy.INCREASE_AUTONOMY_STEP = 10
NDefines.NEconomy.INCREASE_AUTONOMY_MAX = 90
NDefines.NEconomy.AUTONOMY_CHANGE_DURATION = 3650					-- about 30 years
NDefines.NEconomy.LAND_TECH_MAINTENANCE_IMPACT = 0.05 				-- % each tech increases it.
NDefines.NEconomy.ADVISOR_COST = 0.8								-- Advisor cost modifier
NDefines.NEconomy.GOLD_INFLATION_THRESHOLD = 0.1					-- _EDEF_GOLD_INFLATION_THRESHOLD_
NDefines.NEconomy.GOLD_INFLATION = 0.6								-- _EDEF_GOLD_INFLATION_
NDefines.NEconomy.TREASURE_FLEET_INFLATION = 0.25
NDefines.NEconomy.BASE_YEARLY_INFLATION = 0							-- yearly inflation increase
NDefines.NEconomy.INFLATION_FROM_LOAN = 0.5							-- increase per loan
NDefines.NEconomy.INFLATION_FROM_PEACE_GOLD = 0.04					-- inflation per month of income taken in peace (also applied to province sales)
NDefines.NEconomy.INFLATION_ACTION_REDUCTION = 1					-- amount per action
NDefines.NEconomy.BANKRUPTCY_DURATION = 5							-- _EDEF_BANKRUPTCY_DURATION_
NDefines.NEconomy.BANKRUPTCY_BUILDING_DESTRUCTION_THRESHOLD = 0		-- Bankruptcy will destroy building that have been build in the latest X amount of years. Set to zero to disable the destruction mechanic.
NDefines.NEconomy.BANKRUPTCY_PROVINCE_DEVASTATION_GAIN = 0			-- Devastation gained in country provinces after declaring bankrutcy.
NDefines.NEconomy.WARTAXES_DURATION = 12							-- _EDEF_WARTAXES_DURATION_
NDefines.NEconomy.MINIMUM_INTERESTS = 1								-- _EDEF_MINIMUM_INTERESTS_
NDefines.NEconomy.BASE_INTERESTS = 8								-- Base interests
NDefines.NEconomy.LAND_MAINTENANCE_FACTOR = 0.1						-- _EDEF_LAND_MAINTENANCE_FACTOR
NDefines.NEconomy.HEAVY_SHIP_MAINT_FACTOR = 0.03					-- _EDEF_HEAVY_SHIP_MAINT_FACTOR_
NDefines.NEconomy.LIGHT_SHIP_MAINT_FACTOR = 0.03					-- _EDEF_LIGHT_SHIP_MAINT_FACTOR_
NDefines.NEconomy.GALLEY_MAINT_FACTOR = 0.03						-- _EDEF_GALLEY_MAINT_FACTOR_
NDefines.NEconomy.TRANSPORT_MAINT_FACTOR = 0.03						-- _EDEF_TRANSPORT_MAINT_FACTOR_
NDefines.NEconomy.COLONIAL_MAINTENANCE_FACTOR = 1					-- _EDEF_COLONIAL_MAINTENANCE_FACTOR_
NDefines.NEconomy.MISSIONARY_MAINTENANCE_FACTOR = 0					-- How much a missionary costs in itself
NDefines.NEconomy.MISSIONARY_MAINTENANCE_DEVELOPMENT_FACTOR = 0.5	-- How much this is ncreased from development
NDefines.NEconomy.MISSIONARY_MAINTENANCE_AUTONOMY_FACTOR = 0		-- How much this is ncreased from local autonomy
NDefines.NEconomy.MISSIONARY_MAINTENANCE_AUTONOMY_BASE = 0.1		-- The local autonomy is added to this base in the formula.
NDefines.NEconomy.MISSIONARY_MAINTENANCE_DEVELOPMENT_CAP = 45		-- Where dev will get capped by the system for calculations.
NDefines.NEconomy.MERCHANT_TIME_DISTANCE = 0.25						-- _EDEF_MERCHANT_TIME_DISTANCE_
NDefines.NEconomy.MERCHANT_CHANCE = 0.35							-- _EDEF_MERCHANT_CHANCE_
NDefines.NEconomy.MERCHANT_COMPETE = 0.5							-- _EDEF_MERCHANT_COMPETE_
NDefines.NEconomy.MAX_PROVINCE_SELL_PRICE = 100						-- _EDEF_MAX_PROVINCE_SELL_PRICE_
NDefines.NEconomy.COLONIST_DISTANCE_DIVISOR = 1000					-- _EDEF_COLONIST_DISTANCE_DIVISOR_
NDefines.NEconomy.COLONIST_TIME = 0.3								-- _EDEF_COLONIST_TIME_
NDefines.NEconomy.COLONIST_CHANCE = 0.025							-- _EDEF_COLONIST_CHANCE_
NDefines.NEconomy.MISSIONARY_TIME_BASE = 1000						-- _EDEF_MISSIONARY_TIME_BASE = 10
NDefines.NEconomy.MISSIONARY_TIME_DISTANCE = 0.2					-- _EDEF_MISSIONARY_TIME_DISTANCE = 10
NDefines.NEconomy.TRADE_WIND_STRENGTH = 0.5							-- _EDEF_TRADE_WIND_STRENGTH_
NDefines.NEconomy.MERCHANT_COMPETE_PERCENT_OWNED_BASE = 0.25		-- _EDEF_MERCHANT_COMPETE_PERCENT_OWNED_BASE_
NDefines.NEconomy.TRADED_FRACTION_FOR_BONUS = 2						-- _EDEF_TRADED_FRACTION_FOR_BONUS_
NDefines.NEconomy.OPEN_SEA_MODIFIER = 1.7							-- _EDEF_OPEN_SEA_MODIFIER_
NDefines.NEconomy.COASTAL_MODIFIER = 0.7							-- _EDEF_COASTAL_MODIFIER_
NDefines.NEconomy.TRADE_CAPITAL_POWER = 0.5							-- TRADE_CAPITAL_POWER
NDefines.NEconomy.MERCHANT_SPEED = 20								-- MERCHANT_SPEED
NDefines.NEconomy.MERCHANT_MAX_POWER_BONUS = 0.5					-- MERCHANT_MAX_POWER_BONUS
NDefines.NEconomy.TRADE_SHIP_MAX_DAYS_IN_PORT = 5					-- TRADE_SHIP_MAX_DAYS_IN_PORT
NDefines.NEconomy.TRADE_SHIP_ORG_LIMIT = 0.5						-- TRADE_SHIP_ORG_LIMIT
NDefines.NEconomy.TRADE_NON_CAPITAL_OFFICE = -0.6					-- TRADE_NON_CAPITAL_OFFICE
NDefines.NEconomy.TRADE_MERCHANT_PRESENT = 0.15						-- bonus on income if trade present
NDefines.NEconomy.EMBARGO_BASE_EFFICIENCY = 0.5						-- EMBARGO_BASE_EFFICIENCY
NDefines.NEconomy.EMBARGO_MERCANTILISM_EFFICIENCY = 50				-- Percentage added to embargo efficiency modifier scaled by mercantilism.
NDefines.NEconomy.TRADE_ADDED_VALUE_MODIFER = 0.065
NDefines.NEconomy.TRADE_PROPAGATE_DIVIDER = 5
NDefines.NEconomy.TRADE_PROPAGATE_THRESHOLD = 1
NDefines.NEconomy.REGAIN_COST_BEFORE_PROGRESS = 0.1					-- Before what percentage will the full cost be regained
NDefines.NEconomy.ALLOW_DESTROY_MANUFACTORY = 1						-- Should the player be permitted to destroy manufactories?
NDefines.NEconomy.PIRATES_TRADE_POWER_FACTOR = 1.5
NDefines.NEconomy.PIRATES_MONOPOLY_BONUS = 2						-- Factor of monopolization of node added to privateer power efficiency.
NDefines.NEconomy.TRADE_COMPANY_CONTROL_LIMIT = 0.6
NDefines.NEconomy.TRADE_COMPANY_DAYS_TO_SWAP_LEADER = 30
NDefines.NEconomy.TRADE_COMPANY_STRONG_LIMIT = 0.34
NDefines.NEconomy.TRADE_COMPANY_COOLDOWN = 60
NDefines.NEconomy.LARGE_COLONIAL_NATION_LIMIT = 99
NDefines.NEconomy.PRIVATEER_INCOME_COLLECTION_EFF = 0.7
NDefines.NEconomy.MIN_ARMY_MAINTENANCE = 0.1
NDefines.NEconomy.MIN_NAVY_MAINTENANCE = 0.1
NDefines.NEconomy.CARAVAN_FACTOR = 50								-- Development is divided by this factor, do not set to zero!
NDefines.NEconomy.CARAVAN_POWER_MAX = 15
NDefines.NEconomy.CARAVAN_POWER_MIN = 0
NDefines.NEconomy.MAX_BUILDING_SLOTS = 20							-- Maximum number of buildings slots, i.e. max buildings possible.
NDefines.NEconomy.COT_BUILDING_SLOTS = 2							-- Number of slots used by a Center of Trade.
NDefines.NEconomy.COT_DOWNGRADE_PRESTIGE_COST = -10					-- Cost in prestige to downgrade a Center of Trade.
NDefines.NEconomy.MAX_LD_FOR_CONSTRUCT_IN_SUBJECT = 50				-- Maximum liberty desire at which an overlord can recruit regiments and build ships in a subject's glorious lands.
NDefines.NEconomy.CONSTRUCT_IN_SUBJECT_TIME_MULTIPLIER = 1.25
NDefines.NEconomy.BANK_LOAN_DURATION = 60							-- Default bank loan duration in months
NDefines.NEconomy.MIN_NEW_CACHED_STARTING_INCOME = 1				-- Minimum historic starting income for newly created/released countries
NDefines.NEconomy.EXPELLED_MINORITY_DEV_BONUS_FACTOR = 0.2			-- Bonus development on minority expulsion completion, multiplied by origin province development
NDefines.NEconomy.EXPELLING_MINORITY_COLONIST_COST_FACTOR = -0.5	-- Colonist maintenance cost factor when expelling minority
NDefines.NEconomy.EXPELLING_MINORITY_SETTLER_CHANCE_FACTOR = 0.005	-- Settler chance bonus when expelling minority, multiplied by origin province development
