
NDefines.NAI.ACCEPTABLE_BALANCE_DEFAULT = 1.1 									-- AI wants this advantage to enter battles typically (there are some exceptions, e.g. offensives).
																				-- Rosth: was 1.3 in 2.52.06. Vanilla value is 1.7. Every AI stack assesses the value for a specific province based on the number and distance of allied/enemy regiments near the target province (max. 4 provinces away) and divides it by a pre-set value based on a terrain combat roll advantage/disadvantage (0.84 for own -2, 1.12 for own -1, 1.4 for neutral terrain, 1.54 for enemy -1, 1.68 for enemy -2). This value can be seen by typing "mapmode aieval" in the console and hovering over a province. Then it compares it to ACCEPTABLE_BALANCE_DEFAULT^(-1) (0.909 if the define is set to 1.1). If it is higher, it would not move into that province. Note that the first value heavily favors big stacks and the pre-set value for neutral terrain is allegedly not 1.4 but ~1 due to a bug.
NDefines.NAI.ACCEPTABLE_BALANCE_FRIEND_IN_COMBAT = 0.75
NDefines.NAI.EDICT_VALUE_THRESHOLD = 120 										-- The higher this value, the less the AI will use Edicts
NDefines.NAI.EDICT_VALUE_THRESHOLD_MULTIPLY_DEFICIT = 10 						-- Change to above threshold in case of running deficit
NDefines.NAI.EDICT_VALUE_THRESHOLD_MULTIPLY_LOW_INCOME = 3 						-- Change to above threshold in case of low income
NDefines.NAI.PRESS_THEM_FURTHER = 1												-- This makes AI that has been promised land require that the enemy is pressed further if they think it is possible. Set to 1 to activate
NDefines.NAI.CALL_ACCEPTANCE_COALITION_VS_SUBJECT = -60							-- Acceptance penalty when an AI's Tributary (or currently non-existing Subject type with similar mechanic) calls to war against someone who is in a coalition against them
NDefines.NAI.WANT_TRIBUTARY_LOST_MANDATE = 25									-- How important it is for Celestial Emperor to make tributaries out of neighbors.
NDefines.NAI.MIN_CAV_PERCENTAGE = 10											-- AI will always try to have at least this many % of their army as cav, regardless of time in the game.
NDefines.NAI.MAX_CAV_PERCENTAGE = 40											-- For modding, actual ratio is dynamically computed but will be no higher than this.
NDefines.NAI.FOG_OF_WAR_FORGET_CHANCE = 0.1										-- Daily percentage chance of AI forgetting a unit that's hidden in Fog of War.
																				-- Rosth: Vanilla value is 1. AI cheating with vision is annoying, but lowering this value would make the AI less skittish when deciding when and how to move it's army.
NDefines.NAI.DIPLOMATIC_ACTION_ABANDON_UNION_BASE_FACTOR = 60					-- AI scoring to abandoning Personal Union (given high enough LD and strength).
NDefines.NAI.DIPLOMATIC_ACTION_ABANDON_UNION_STRENGTH_THRESHOLD = 3				-- Threshold in relative strength for AI to give up on Personal Union.
NDefines.NAI.DEVELOP_IN_SUBJECTS_PREFERENCE = 0.75								-- At 1, AI likes developing subjects approximately the same as its own provinces (more or less depending on their Liberty Desire).
NDefines.NAI.POWERBALANCE_DISABLE_VERSUS_AI = 0									-- If set to 1, AI will never pick another AI nation as a powerbalance threat.
NDefines.NAI.POWERBALANCE_DISABLE_VERSUS_PLAYER = 0								-- If set to 1, AI will never (directly) pick a human player nation as a powerbalance threat.
NDefines.NAI.GREAT_POWER_ACTIONS_DISABLE_VERSUS_PLAYER = 0						-- If set to 1, AI will never perform Great Power actions (directly) hurting a human player.
NDefines.NAI.DIPLOMATIC_ACTION_ALLIANCE_POWERBALANCE_FACTOR = 50				-- AI scoring for alliance action is increased by this if a nation blocks a powerbalance threat.
NDefines.NAI.DIPLOMATIC_ACTION_GUARANTEE_POWERBALANCE_FACTOR = 80				-- AI scoring for guarantee action is increased by this if a nation blocks a powerbalance threat.
NDefines.NAI.DIPLOMATIC_ACTION_GIFT_POWERBALANCE_FACTOR_AI = 100				-- AI willingness to send gifts to AI nations fighting power balance threat is modulated by this.
NDefines.NAI.DIPLOMATIC_ACTION_GIFT_POWERBALANCE_FACTOR_PLAYER = 50				-- AI willingness to send gifts to human nations fighting power balance threat is modulated by this.
NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_POWERBALANCE_FACTOR = 40				-- AI scoring to give subsidies to nations blocking/fighting power balance threat.
NDefines.NAI.DIPLOMATIC_ACTION_CRUSADE_POWERBALANCE_FACTOR = 40					-- AI scoring for calling crusade on power balance threat.
NDefines.NAI.DIPLOMATIC_ACTION_EXCOMMUNICATE_POWERBALANCE_FACTOR = 40			-- AI scoring for excommunicating power balance threat.
NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_ONLY_MILITARY_RULERS = 1		-- If set to 1, AI will only send Condottieri while having a miliaristic ruler.
NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_ONLY_NEIGHBORS = 1				-- If set to 1, AI will only send Condottieri to neighbors, regardless of access.
NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_DISABLE_VERSUS_PLAYER_ENEMIES = 0	-- If set to 1, AI will try avoid sending Condottieri having to fight against human player enemies.
NDefines.NAI.DIPLOMATIC_ACTION_BREAK_ALLIANCE_BASE_FACTOR = 1000				-- AI's will to remove allies of target it is declaring war on, will however be divided by relative strength compared to them.
NDefines.NAI.DIPLOMATIC_ACTION_TAKE_ON_DEBT_BASE_FACTOR = 10					-- AI base scoring for Take on Foreign Debt (needs to be ally or block rival/power balance threat to even apply).
NDefines.NAI.DIPLOMATIC_ACTION_TAKE_ON_DEBT_ALLY_FACTOR = 30					-- AI additional scoring for Take on Foreign Debt with nations we are allied to.
NDefines.NAI.DIPLOMATIC_ACTION_TAKE_ON_DEBT_POWERBALANCE_FACTOR = 20			-- AI additional scoring for Take on Foreign Debt for targets that block powerbalance threat.
NDefines.NAI.DIPLOMATIC_ACTION_TAKE_ON_DEBT_ANTI_RIVAL_FACTOR = 30				-- AI additional scoring for Take on Foreign Debt for targets that block at least one rival.
NDefines.NAI.DIPLOMATIC_ACTION_TAKE_ON_DEBT_MONTHLY_INCOME = 6					-- Limit on number of months of income AI wants to spend on a single Take on Foreign Debt action.
NDefines.NAI.DIPLOMATIC_ACTION_INFLUENCE_NATION_BASE_FACTOR = 20				-- AI base scoring for Influence Nation (needs to be ally or block rival/power balance threat to even apply).
NDefines.NAI.DIPLOMATIC_ACTION_INFLUENCE_NATION_ALLY_FACTOR = 30				-- AI additional scoring for Influence Nation with nations we are allied to.
NDefines.NAI.DIPLOMATIC_ACTION_INFLUENCE_NATION_POWERBALANCE_FACTOR = 20		-- AI additional scoring for Influence Nation for targets that block powerbalance threat.
NDefines.NAI.DIPLOMATIC_ACTION_INFLUENCE_NATION_ANTI_RIVAL_FACTOR = 30			-- AI additional scoring for Influence Nation for targets that block at least one rival.
NDefines.NAI.DIPLOMATIC_ACTION_INFLUENCE_NATION_MONTHLY_INCOME = 6				-- Limit on number of months of income AI wants to spend on a single TInfluence Nation action.
NDefines.NAI.DIPLOMATIC_ACTION_INFLUENCE_NATION_MAX_COST_PER_MP = 0.4			-- Max number of ducats (as per initial cost) per monarch point (as per the maximum duration of Influence Nation) AI is willing to pay.
NDefines.NAI.ONLY_INFANTRY_MERCS = 1											-- Set to 0 to let AI hire artillery and cavalry mercenaries.
NDefines.NAI.FORT_MAINTENANCE_CHEAT = 0											-- Set to 0 to disable AI fort maintenance cheating. Warning: Will make AI suck.
NDefines.NAI.AI_USES_HISTORICAL_IDEA_GROUPS = 1									-- If set to 0, ai will use ai_will_do instead of historical ideagroups when picking ideagroups (ai never uses historical ideagroups in custom/random setup)
NDefines.NAI.AI_CONVERT_CULTURES = 0											-- If set to 0, AI will not convert cultures
NDefines.NAI.VASSAL_FABRICATE_CLAIMS = 1										-- If set to 1, subjects will use fabricate claims on foreign powers
NDefines.NAI.VASSAL_BUY_ANY_PROVINCE = 0										-- If set to 1, vassals will agree to buying a province from their overlord even if they lack an interest in it
NDefines.NAI.AI_BUY_PROVINCE_MAX_OE = 50										-- % of OE (including OE from sold province) above which AI who is NOT a subject will not buy non-core provinces (Not used if OE is at 0)
NDefines.NAI.AI_BUY_PROVINCE_SUBJECT_MAX_OE = 75								-- % of OE (including OE from sold province) above which AI who is a subject will not buy non-core provinces (Not used if OE is at 0)
NDefines.NAI.SUBSIDY_YEARS = 10													-- Years AI will give subsidies for
NDefines.NAI.MIN_INCOME_FOR_SUBSIDIES = 25										-- Minimum monthly income for AI to want to spend some on subsidies.
																				-- Rosth: let's have the AI sort out it's own problems before helping anyone else, shall we?
NDefines.NAI.PS_SHORT_TERM_POOL = 150											-- Max power AI will store in its short-term spending pool
NDefines.NAI.AGGRESSIVENESS = 1000												-- Base chance (out of 10000) of AI being willing to start a war each diplomatic tick.
																				-- Rosth: refer to EVENT_PROCESS_OFFSET define (which is 30 in M&T). Means 1000/10000 *base* chance (10%) to declare a war on a suitable target every 30 days.
NDefines.NAI.AGGRESSIVENESS_BONUS_EASY_WAR = 2000								-- Added to aggressiveness if the war is against a weak or particularily hated enemy.
																				-- Rosth: refer to EVENT_PROCESS_OFFSET define (which is 30 in M&T). Means (1000+2000)/10000 *base* chance (30%) to declare a war on a suitable target every 30 days.
NDefines.NAI.MISSION_PICK_CHANCE = 33											-- Monthly chance of AI picking a mission if it lacks one (of 100)
NDefines.NAI.TRADE_INTEREST_THRESHOLD = 4										-- Number of merchants required to be a nation with trade interest
NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS = 6									-- AI must have at least this many monthly deficits of savings to be willing to deficit spend
NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS_PEACETIME = 48							-- Same as DEFICIT_SPENDING_MIN_MONTHS, but during peacetime, no rebels and no war exhaustion
NDefines.NAI.BIGSHIP_FRACTION = 0.25											-- The proportion of big ships in an AI navy of light ships and big ships (for coastal sea countries, this fraction is mostly galleys).
																				-- Rosth: "big" ships are heavies and galleys.
NDefines.NAI.ARTILLERY_FRACTION = 0.16 											-- Ratio of artillery to infantry AI will build
NDefines.NAI.FORCE_COMPOSITION_CHANGE_TECH_LEVEL = 22							-- Tech level at which AI will double its artillery fraction
NDefines.NAI.TRANSPORT_FRACTION = 0.4											-- Max fraction of naval forcelimit that should be transports
NDefines.NAI.INCOME_SAVINGS_FRACTION = 0.6										-- AI will reserve this amount of their surplus for long-term savings
NDefines.NAI.OVER_FORCELIMIT_AVOIDANCE_FACTOR = 250								-- The higher this number is, the less willing the AI will be to exceed forcelimits
NDefines.NAI.DESIRED_SURPLUS = 0.4												-- AI will aim for having at least this fraction of their income as surplus when they don't have large savings
NDefines.NAI.DESIRED_DEFICIT = 0.01												-- AI will try to spend this fraction of their money above their target for long term savings.
NDefines.NAI.EXTRA_SURPLUS_WHEN_NEEDING_BUILDINGS = 0							-- AI will aim for having at least this fraction of their income as additional surplus when they need buildings
NDefines.NAI.MAX_SAVINGS = 1000													-- AI will keep a maximum of this * their monthly income in long-term savings
NDefines.NAI.ADVISOR_BUDGET_FRACTION = 0.25										-- AI will spend a maximum of this fraction of monthly income on advisor maintenance
NDefines.NAI.CORRUPTION_BUDGET_FRACTION = 0										-- AI will spend a maximum of this fraction of monthly income on rooting out corruption
NDefines.NAI.COLONY_BUDGET_FRACTION = 0.75										-- AI will spend a maximum of this amount of monthly ducats for colonies.
NDefines.NAI.ARMY_BUDGET_FRACTION = 0.5											-- AI will spend a maximum of this fraction of monthly income on army maintenance (based off wartime costs)
NDefines.NAI.NAVY_BUDGET_FRACTION = 0.4											-- AI will spend a maximum of this fraction of monthly income on navy maintenance (based off wartime costs)
NDefines.NAI.FORT_BUDGET_FRACTION = 0.2											-- AI will spend a maximum of this fraction of monthly income on forts
NDefines.NAI.REGIMENTS_PER_GENERAL = 10											-- AI will want one general for every this number of regiments (will not exceed free leader pool)
NDefines.NAI.MIN_SHIPS_FOR_ADMIRAL = 16											-- The minimum navy size for the AI to bother with an admiral
NDefines.NAI.REGIMENTS_FOR_CONQUISTADOR = 2										-- The maximum size of army AI will use for an exploring conquistador.
NDefines.NAI.CANCEL_CONSTRUCTION_SIEGE_PROGRESS = 0								-- If chance of fort falling is at least this, AI will cancel constructions in the province
NDefines.NAI.DIPLOMATIC_INTEREST_DISTANCE = 100									-- If border distance is greater than this, diplomatic AI will have less interest in the country
NDefines.NAI.CONQUEST_INTEREST_DISTANCE = 300 									-- Beyond this range, AI is less interested in conquest of provinces.
																				-- Rosth: assuming this refers to range from the capital, otherwise this wouldn't make much sense. Vanilla value is 100. 
NDefines.NAI.FORCE_MARCH_MIN_SIZE = 5											-- AI will not force march units with less regiments than this
NDefines.NAI.FORCE_MARCH_ALWAYS_SIZE = 10000									-- AI will always try to force march units of at least this size (disabled)
NDefines.NAI.MAX_BUILDING_COST_INCOME_MONTHS = 100								-- AI will not save up for a building that costs more than their monthly income * this, if there are cheaper alternatives
NDefines.NAI.PURSUE_DISTANCE = 70												-- AI will not pursue armies retreating to a province further away than this.
																				-- Rosth: "distance" refers to the distance between a province in which the stack is currently in and the province to which the enemy stack is retreating. For the reference, 100 is about the distance from Paris to Guiana/Vales/Westfalen. 70 is about the distance from Paris to Haut-Poetou/Milieu/Limburg. This is meant to stop the AI from chasing around retreating stacks while wasting time and suffering attrition and make it spend that time to actually siege provinces.
NDefines.NAI.CALL_IN_ALLIES_POWER_RATIO = 4										-- AI will only call in allies in an offensive war if their military power ratio to the enemy is less than this
NDefines.NAI.POWERFUL_ALLY_PENALTY = 50											-- Penalty on alliance for them already having a powerful ally if much stronger
NDefines.NAI.RIVAL_ALLIANCE_PENALTY = 50										-- Penalty on alliance chance for being allied to rivals

NDefines.NAI.DEVELOPMENT_CAP_BASE = 3											-- AI will not develop provinces that have more development than this or DEVELOPMENT_CAP_MULT*original development (whichever is bigger)
NDefines.NAI.DEVELOPMENT_CAP_MULT = 1

NDefines.NAI.PEACE_BASE_RELUCTANCE = 0											-- AI base stubbornness to refuse peace (always applied)
NDefines.NAI.PEACE_BATTLE_RELUCTANCE = 60										-- Reluctance multiplied by fraction of support limit currently in an ongoing battle in this war (to encourage battle resolution before peacing).
NDefines.NAI.PEACE_EXCESSIVE_DEMANDS_FACTOR = 0.01								-- AI unwillingness to peace based on demanding more stuff than you have warscore
NDefines.NAI.PEACE_EXCESSIVE_DEMANDS_THRESHOLD = 30								-- If you have less warscore than this, excessive demands will be factored in more highly
NDefines.NAI.PEACE_TIME_MONTHS = 48												-- Months of additional AI stubbornness in a war
NDefines.NAI.PEACE_TIME_MAX_MONTHS = 600										-- Max months applied to time factor in a war
NDefines.NAI.PEACE_TIME_EARLY_FACTOR = 0.32										-- During months of stubbornness the effect of time passed is multiplied by this
NDefines.NAI.PEACE_TIME_LATE_FACTOR = 0.5										-- After months of stubbornness the effect of time passed is multiplied by this (only applied to positive war enthusiasm)
NDefines.NAI.PEACE_STALLED_WAR_TIME_FACTOR = 0.34								-- Applied to number of years war has been stalled to determine how much positive war enthusiasm is reduced
NDefines.NAI.PEACE_STALLED_WAR_THRESHOLD = 3									-- If the warscore has changed by this amount or less in the last year, the war is stalled
NDefines.NAI.PEACE_WAR_EXHAUSTION_FACTOR = 1.4									-- AI willingness to peace based on war exhaustion
NDefines.NAI.PEACE_HIGH_WAR_EXHAUSTION_THRESHOLD = 10							-- Threshold for when PEACE_HIGH_WAR_EXHAUSTION_FACTOR is applied
NDefines.NAI.PEACE_HIGH_WAR_EXHAUSTION_FACTOR = 2								-- Additional AI willingness to peace based on war exhaustion above the high threshold
NDefines.NAI.PEACE_WAR_DIRECTION_FACTOR = 0.8									-- AI willingness to peace based on who's making gains in the war
NDefines.NAI.PEACE_WAR_DIRECTION_WINNING_MULT = 3								-- Multiplies AI emphasis on war direction if it's the one making gains
NDefines.NAI.PEACE_FORCE_BALANCE_FACTOR = 0.2									-- AI willingness to peace based on strength estimation of both sides
NDefines.NAI.PEACE_INDEPENDENCE_FACTOR = 50										-- Revolting AI's unwillingness to peace while between -5 and cost of independence wargoal in an independence war.
NDefines.NAI.PEACE_WARGOAL_FACTOR = 0											-- AI unwillingness to peace based on holding the wargoal
NDefines.NAI.PEACE_CAPITAL_FACTOR = 0											-- AI unwillingness to peace based on holding their own capital
NDefines.NAI.PEACE_MILITARY_STRENGTH_FACTOR = 10								-- AI unwillingness to peace based on manpower & forcelimits
NDefines.NAI.PEACE_ALLY_BASE_RELUCTANCE_MULT = 2								-- Multiplies PEACE_BASE_RELUCTANCE for allies in a war
NDefines.NAI.PEACE_ALLY_WARSCORE_MULT = 0.6										-- How much extra war enthusiasm from overall warscore allies in a war get
NDefines.NAI.PEACE_ALLY_TIME_MULT = 0.8											-- Multiplies PEACE_TIME_FACTOR for allies in a war
NDefines.NAI.PEACE_ALLY_EXCESSIVE_DEMANDS_MULT = 2								-- Multiplies PEACE_EXCESSIVE_DEMANDS_FACTOR for allies in a war
NDefines.NAI.PEACE_ALLY_WAR_EXHAUSTION_MULT = 1									-- Multiplies PEACE_WAR_EXHAUSTION_FACTOR for allies in a war
NDefines.NAI.PEACE_ALLY_WAR_DIRECTION_MULT = 0									-- Multiplies PEACE_WAR_DIRECTION_FACTOR for allies in a war
NDefines.NAI.PEACE_ALLY_FORCE_BALANCE_MULT = 0									-- Multiplies PEACE_FORCE_BALANCE_FACTOR for allies in a war
NDefines.NAI.PEACE_ALLY_WARGOAL_MULT = 0										-- Multiplies PEACE_WARGOAL_FACTOR for allies in a war
NDefines.NAI.PEACE_ALLY_CAPITAL_MULT = 1										-- Multiplies PEACE_CAPITAL_FACTOR for allies in a war
NDefines.NAI.PEACE_ALLY_MILITARY_STRENGTH_MULT = 2								-- Multiplies PEACE_MILITARY_STRENGTH_FACTOR for allies in a war
NDefines.NAI.PEACE_OTHER_WAR_FORCE_BALANCE_MULT = 0.5							-- Multiplies the force balance of other countries who are involved in a different war with either side
NDefines.NAI.PEACE_INCONCLUSIVE_THRESHOLD = 10									-- no demands will be accepted by AI if under this warscore
NDefines.NAI.PEACE_DESPERATION_FACTOR = 40										-- AI willingness to peace based on desperation from occupied homelands
NDefines.NAI.PEACE_ALLY_DESPERATION_MULT = 0.75									-- Multiplies PEACE_DESPERATION_FACTOR for allies in a war
NDefines.NAI.PEACE_REBELS_FACTOR = 20											-- AI willingness to peace based on number of revolts in their provinces
NDefines.NAI.PEACE_COALITION_FACTOR = 20										-- AI unwillingness to peace based on being in a coalition war
NDefines.NAI.PEACE_ALLY_REBELS_MULT = 0.5										-- Multiplies PEACE_REBELS_FACTOR for allies in a war
NDefines.NAI.PEACE_DESIRE_AI_PREFS_QUICK_PEACE = 100							-- How much AI wants to peace out when player enabled AI setting "Seek Quick Peace"
NDefines.NAI.PEACE_CALL_FOR_PEACE_FACTOR = 10									-- How much AI wants peace based on having call for peace

NDefines.NAI.PEACE_TERMS_BASE_SCORE = 10										-- Base AI scoring for any peace demand
NDefines.NAI.PEACE_RANDOM_FACTOR = 0.75											-- How much randomness is applied to AI weighting (as a fraction of the goal score)
NDefines.NAI.PEACE_TERMS_CB_MULT = 2											-- AI desire for a wargoal is multiplied by this for having the right CB
NDefines.NAI.PEACE_TERMS_STRATEGY_MULT = 0.85									-- AI desire for a wargoal is multiplied by this if it doesn't fit into their general strategy
NDefines.NAI.PEACE_TERMS_MIN_SCORE = 1											-- AI "does not want" peace treaties that get a lower score than this (modified by ai personality)

NDefines.NAI.PEACE_TERMS_REVOKE_ELECTOR_BASE_MULT = 1000						-- only applied if CB is valid for it
NDefines.NAI.PEACE_TERMS_INDEPENDENCE_BASE_MULT = 10000							-- only applied if CB is valid for it
NDefines.NAI.PEACE_TERMS_UNION_BASE_MULT = 1000									-- only applied if CB is valid for it
NDefines.NAI.PEACE_TERMS_VASSAL_BASE_MULT = 500									-- only applied if the AI has vassalize priority
NDefines.NAI.PEACE_TERMS_TAKE_MANDATE_BASE_MULT = 1000
NDefines.NAI.PEACE_TERMS_CHANGE_GOVERNMENT_BASE_MULT = 0.5						-- only applied if CB is valid for it
NDefines.NAI.PEACE_TERMS_CHANGE_RELIGION_BASE_MULT = 100						-- only applied if CB is valid for it
NDefines.NAI.PEACE_TERMS_ANNEX_BASE_MULT = 100
NDefines.NAI.PEACE_TERMS_PROVINCE_BASE_MULT = 1.2
NDefines.NAI.PEACE_TERMS_TRADE_POWER_BASE_MULT = 1
NDefines.NAI.PEACE_TERMS_HUMILIATE_BASE_MULT = 1
NDefines.NAI.PEACE_TERMS_REVOKE_CORES_BASE_MULT = 1
NDefines.NAI.PEACE_TERMS_REVOKE_REFORM_BASE_MULT = 1
NDefines.NAI.PEACE_TERMS_RETURN_CORES_BASE_MULT = 1
NDefines.NAI.PEACE_TERMS_RELEASE_VASSALS_BASE_MULT = 0.75
NDefines.NAI.PEACE_TERMS_TRANSFER_VASSALS_BASE_MULT = 0.75
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_BASE_MULT = 0.75
NDefines.NAI.PEACE_TERMS_ANNUL_TREATIES_BASE_MULT = 1
NDefines.NAI.PEACE_TERMS_GOLD_BASE_MULT = 0.1
NDefines.NAI.PEACE_TERMS_GIVE_UP_CLAIM = 0
NDefines.NAI.PEACE_TERMS_GIVE_UP_CLAIM_PERMANENT = 0.75
NDefines.NAI.PEACE_TERMS_CONCEDE_DEFEAT_BASE_MULT = 0.1
NDefines.NAI.PEACE_TERMS_DISMANTLE_REVOLUTION_BASE_MULT = 1000
NDefines.NAI.PEACE_TERMS_CHANGE_HRE_RELIGION_BASE_MULT = 1000
NDefines.NAI.PEACE_TERMS_HUMILIATE_RIVAL_BASE_MULT = 1
NDefines.NAI.PEACE_TERMS_ENFORCE_REBEL_DEMANDS_BASE_MULT = 1000
NDefines.NAI.PEACE_TERMS_TRIBUTARY_BASE_MULT = 5								-- Multiplies with strategic interest of making them our Tributary

NDefines.NAI.PEACE_TERMS_PROVINCE_IMPERIAL_LIBERATION_MULT = 0.25				-- AI Emperor's desire for a province is multiplied by this if this is an Imperial Liberation CB war.
NDefines.NAI.PEACE_TERMS_PROVINCE_NO_CB_MULT = 0.8								-- AI desire for a province is multiplied by this if it doesn't have a valid cb for it (only used when annexing, not applied to cores)
NDefines.NAI.PEACE_TERMS_PROVINCE_CORE_MULT = 3									-- AI desire for a province is multiplied by this if it has a core on it
NDefines.NAI.PEACE_TERMS_PROVINCE_WARGOAL_MULT = 2								-- AI desire for a province is multiplied by this if it is the wargoal
NDefines.NAI.PEACE_TERMS_PROVINCE_CLAIM_MULT = 2								-- AI desire for a province is multiplied by this if it has a claim on it
NDefines.NAI.PEACE_TERMS_PROVINCE_NOT_CULTURE_MULT = 0.8						-- AI desire for a province is multiplied by this if it is not the same culture
NDefines.NAI.PEACE_TERMS_PROVINCE_VASSAL_MULT = 0.75							-- AI desire for a province is multiplied by this if it would go to their vassal instead of themselves
NDefines.NAI.PEACE_TERMS_PROVINCE_REAL_ADJACENT_MULT = 0.5						-- AI desire for a province is increased by this multiplier for each owned adjacent province
NDefines.NAI.PEACE_TERMS_PROVINCE_NOT_ADJACENT_MULT = 0.5						-- AI desire for a province is multiplied by this if it is not adjacent at all (including vassals and other provinces being taken in peace)
NDefines.NAI.PEACE_TERMS_PROVINCE_NO_INTEREST_MULT = 0.3						-- AI desire for a province is multiplied by this if it is not on their conquest list
NDefines.NAI.PEACE_TERMS_PROVINCE_OVEREXTENSION_MIN_MULT = 0.75					-- AI desire for a province is multiplied by this if it has 99% overextension (not applied to cores)
NDefines.NAI.PEACE_TERMS_PROVINCE_OVEREXTENSION_MAX_MULT = 1.5					-- AI desire for a province is multiplied by this if it has 0% overextension (not applied to cores)
NDefines.NAI.PEACE_TERMS_PROVINCE_ISOLATED_CAPITAL_MULT = 0.9					-- AI desire for a province if it is capital (costs a bit more to take)
NDefines.NAI.PEACE_TERMS_PROVINCE_ALLY_MULT = 0.5								-- AI desire for giving (non-core) provinces to its allies
NDefines.NAI.PEACE_TERMS_PROVINCE_IMPORTANT_ALLY_MULT = 2						-- AI desire for giving provinces to allies that it has promised land
NDefines.NAI.PEACE_TERMS_TRADE_POWER_VALUE_MULT = 0.1							-- AI desire for transfering trade power is multiplied by this for each 0.1 trade value in shared nodes
NDefines.NAI.PEACE_TERMS_TRADE_POWER_VALUE_MAX = 2								-- Max AI desire for transfering trade power from shared node value
NDefines.NAI.PEACE_TERMS_TRADE_POWER_NO_TRADE_INTEREST_MULT = 0.9				-- AI desire for transfering trade power is multiplied by this if they are not a merchant republic
NDefines.NAI.PEACE_TERMS_HUMILIATE_VALUE_MULT = 1								-- AI desire for humiliating is multiplied by this for each 1 prestige the enemy has
NDefines.NAI.PEACE_TERMS_HUMILIATE_VALUE_MAX = 2								-- Max AI desire for humiliating its' enemy
NDefines.NAI.PEACE_TERMS_REVOKE_CORE_VASSAL_MULT = 0.75							-- AI desire for revoking cores is multiplied by this if the cores are on their vassal instead of themselves
NDefines.NAI.PEACE_TERMS_REVOKE_CORE_FEAR_MULT = 2								-- AI desire for revoking cores is multiplied by this if they are afraid of the other country
NDefines.NAI.PEACE_TERMS_RETURN_CORES_VASSAL_MULT = 2							-- AI desire for returning core provinces is multiplied by this for their vassals
NDefines.NAI.PEACE_TERMS_RETURN_CORES_NOT_FRIEND_MULT = 0.3						-- AI desire for returning core provinces is multiplied by this if they are not friends of the country core is being returned to
NDefines.NAI.PEACE_TERMS_RETURN_CORES_IMPERIAL_LIBERATION_MULT = 2				-- AI desire for returning core province is multiplied by this if it's a target of Imperial Liberation CB war.
NDefines.NAI.PEACE_TERMS_ANNUL_TREATIES_NO_INTEREST_MULT = 0.05					-- AI desire for annuling a treaty is multiplied by this if they have no strategic interests in doing so
NDefines.NAI.PEACE_TERMS_PROVINCE_HRE_UNJUSTIFIED_MULT = 0.1					-- AI desire for a province is multiplied by this for HRE provinces if they are a member of the empire and don't have a CB, claim or core to it
NDefines.NAI.PEACE_TERMS_MIN_MONTHS_OF_GOLD = 5									-- If they don't have at least this much warscore worth of gold, prefer concede defeat
NDefines.NAI.PEACE_TERMS_PROVINCE_STRATEGY_THRESHOLD = 1						-- If province has at least this strategic priority, AI values it higher in peace deals
NDefines.NAI.PEACE_TERMS_RETURN_PROVINCE_STRATEGY_MULT = 0.5					-- If we have strategic priority on a province, AI desire to release it to another nation is multiplied by this amount
NDefines.NAI.PEACE_TERMS_EMPEROR_RELEASE_PRINCE = 50							-- This is added, not multiplied
NDefines.NAI.PEACE_TERMS_RELEASE_VASSAL_SIZE_MULT = 0.1							-- AI desire mult for releasing vassal increased by this for each province they hold
NDefines.NAI.PEACE_TERMS_RELEASE_VASSAL_MAX_MULT = 1.3							-- Max AI desire mult for releasing vassals
NDefines.NAI.PEACE_TERMS_RELEASE_VASSAL_HRE_MULT = 2							-- AI desire for releasing a vassal is multiplied by this if both are HRE members
NDefines.NAI.PEACE_TERMS_RELEASE_VASSAL_ELECTOR_MULT = 10						-- AI desire for releasing an elector is multiplied by this for Emperor
NDefines.NAI.PEACE_TERMS_RELEASE_VASSAL_SAME_CULTURE_MULT = 0.65				-- AI desire for releasing a country is multiplied by this if they are the same culture group as releaser
NDefines.NAI.PEACE_TERMS_RELEASE_VASSAL_SAME_CULTURE_GROUP_MULT = 0.75			-- AI desire for releasing a country is multiplied by this if they are the same culture group (but not same culture) as releaser
NDefines.NAI.PEACE_TERMS_TRANSFER_VASSAL_SIZE_MULT = 0.1						-- AI desire mult for releasing vassal increased by this for each province they hold
NDefines.NAI.PEACE_TERMS_TRANSFER_VASSAL_MAX_MULT = 1.3							-- Max AI desire mult for releasing vassals
NDefines.NAI.PEACE_TERMS_TRANSFER_VASSAL_HRE_MULT = 2							-- AI desire for releasing a vassal is multiplied by this if both are HRE members
NDefines.NAI.PEACE_TERMS_TRANSFER_VASSAL_ELECTOR_MULT = 10						-- AI desire for releasing an elector is multiplied by this for Emperor
NDefines.NAI.PEACE_TERMS_TRANSFER_VASSAL_SAME_CULTURE_MULT = 0.65				-- AI desire for releasing a country is multiplied by this if they are the same culture group as releaser
NDefines.NAI.PEACE_TERMS_TRANSFER_VASSAL_SAME_CULTURE_GROUP_MULT = 0.75			-- AI desire for releasing a country is multiplied by this if they are the same culture group (but not same culture) as releaser
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_SIZE_MULT = 0.01						-- AI desire mult for releasing countries is increased by this for each development they hold
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_MAX_MULT = 1.3							-- Max AI desire mult for releasing countries
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_KARMA_LOW_MULT = 1.5					-- AI desire mult when below karma bonus
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_KARMA_VERY_LOW_MULT = 2				-- AI desire mult when karma low enough for penalty
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_HRE_MULT = 2							-- AI desire for releasing a country is multiplied by this if both are HRE members
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_SAME_CULTURE_MULT = 0.65				-- AI desire for releasing a country is multiplied by this if they are the same culture group as releaser
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_SAME_CULTURE_GROUP_MULT = 0.75			-- AI desire for releasing a country is multiplied by this if they are the same culture group (but not same culture) as releaser
NDefines.NAI.PEACE_TERMS_MIL_ACCESS_BASE_MULT = 0								-- AI desire for mil access through peace
NDefines.NAI.PEACE_TERMS_FLEET_BASING_BASE_MULT = 0								-- AI desire for fleet basing rights through peace
NDefines.NAI.PEACE_TERMS_WAR_REPARATIONS_BASE_MULT = 0.4						-- AI desire for war reparations through peace
NDefines.NAI.PEACE_TERMS_WAR_REPARATIONS_MIN_INCOME_RATIO = 0.5					-- AI only wants war reparations if other country has at least this % of their income

NDefines.NAI.DIPLOMATIC_ACTION_RANDOM_FACTOR = 1								-- How much of the AI diplomatic action scoring is randomly determined (1.0 = half random, 2.0 = 2/3rd random, etc)
NDefines.NAI.DIPLOMATIC_ACTION_PROPOSE_SCORE = 50								-- AI must score a diplomatic action at least this highly to propose it themselves
NDefines.NAI.DIPLOMATIC_ACTION_BREAK_SCORE = 30									-- AI must score a diplomatic action less than this to break it off
NDefines.NAI.DIPLOMATIC_ACTION_PERSONALITY_MULT = 1.5							-- How much more the AI values a diplomatic action if it suits their personality (improve relations for diplomat, etc)

NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_BASE_MULT = 33					-- AI scoring for offer condottieri, base scale.
NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_MONTHLY_PARTICIPATION_RATE = -0.1		-- Base monthly decay in participation. Related to multipliers for war participation (but doesn't depend on number of regiments, so raw multiplier matters).
NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_PARTICIPATION_BREAK = -1.5		-- At this level of (lack of) participation from the player, the AI will break the condottieri agreement and tell all their friends.
NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_PARTICIPATION_WARN = -0.8		-- At this level of (lack of) participation from the player, a warning alert will be displayed about impendent AI discontent.
NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_HIRING_MALUS_YEARS = 15		-- Once AI has told all their friends about how mean a player is, they will refuse to hire condottieri for cash this long.
NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_PARTICIPATION_FROM_CASUALTIES = 0.5	-- Scaler for casulties caused by condottieri.
NDefines.NAI.DIPLOMATIC_ACTION_ALLIANCE_ACCEPTANCE_MULT = 3						-- AI scoring for alliance based on willingness to accept it if offered to them
NDefines.NAI.DIPLOMATIC_ACTION_KNOWLEDGE_SHARING_ACCEPTANCE_MULT = 3			-- AI scoring for knowledge sharing based on willingness to accept it if offered to them
NDefines.NAI.DIPLOMATIC_ACTION_SHAREMAP_REGION_SELF_VALUE_MULT = 1.5			-- AI scoring for sharing maps based on "interests in region" for map sharing.
NDefines.NAI.DIPLOMATIC_ACTION_SHAREMAP_PRESTIGE_FACTOR = 0.5					-- AI scoring for sharing maps factor for current prestige.
NDefines.NAI.DIPLOMATIC_ACTION_FEDERATION_ACCEPTANCE_MULT = 3					-- AI scoring for alliance based on willingness to accept it if offered to them
NDefines.NAI.DIPLOMATIC_ACTION_ROYAL_MARRIAGE_ACCEPTANCE_MULT = 2				-- AI scoring for royal marriage based on their willingness to accept it if offered to them
NDefines.NAI.DIPLOMATIC_ACTION_ROYAL_MARRIAGE_NO_POWER_COST_RELATION_MULT = 0.25		-- AI scoring for royal marriage is multiplied by this if they currently lack a relation with a power cost
NDefines.NAI.DIPLOMATIC_ACTION_IMPROVE_RELATIONS_BEFRIEND_FACTOR = 50			-- AI scoring for improve relations is increased by this if they have an attitude with 'befriend' desire
NDefines.NAI.DIPLOMATIC_ACTION_IMPROVE_RELATIONS_ALLY_FACTOR = 50				-- AI scoring for improve relations is increased by this if they have an attitude with 'ally' desire
NDefines.NAI.DIPLOMATIC_ACTION_IMPROVE_RELATIONS_JOIN_HRE_FACTOR = 500			-- AI scoring for improve relations with the emperor is increased by this if they want to join the HRE.
NDefines.NAI.DIPLOMATIC_ACTION_IMPROVE_RELATIONS_VASSALIZE_FACTOR = 150			-- AI scoring for improve relations is increased by this if they have an attitude with 'vassalize' desire (also applied to royal marriage desire)
NDefines.NAI.DIPLOMATIC_ACTION_IMPROVE_RELATIONS_SUPPORTING_HEIR_FACTOR = 50	-- AI scoring for improve relations is increased by this if they are also supporting a heir in the country
NDefines.NAI.DIPLOMATIC_ACTION_GRANT_ELECTORATE_PROVINCE_PENALTY_THRESHOLD = 4	-- AI scoring for grant electorate is reduced if target has at least this many provinces
NDefines.NAI.DIPLOMATIC_ACTION_GRANT_ELECTORATE_PROVINCE_PENALTY_MULT = 0.5		-- AI scoring for grant electorate is multiplied by this for each province above threshold
NDefines.NAI.DIPLOMATIC_ACTION_EMBARGO_TRADE_INTEREST_FACTOR = 25				-- AI scoring for embargo is increased by this if they have trade interest
NDefines.NAI.DIPLOMATIC_ACTION_EMBARGO_WAR_FACTOR = 50							-- AI scoring for embargo is increased by this if they are at war
NDefines.NAI.DIPLOMATIC_ACTION_EMBARGO_TRADE_POWER_THRESHOLD = 1				-- AI will not embargo unless value of shared nodes is at least this high
NDefines.NAI.DIPLOMATIC_ACTION_EMBARGO_TRADE_POWER_FACTOR = 25					-- AI scoring for embargo is increased by this for each 1.0 value in shared nodes
NDefines.NAI.DIPLOMATIC_ACTION_EMBARGO_COALITION_TARGET_MULT = 3				-- AI scoring for embargo is multiplied by this against coalition target
NDefines.NAI.DIPLOMATIC_ACTION_MILITARY_ACCESS_PEACE_MULT = 0.5					-- AI scoring for military access is multiplied by this if at peace
NDefines.NAI.DIPLOMATIC_ACTION_MILITARY_ACCESS_EXISTING_RELATION_MULT = 2		-- AI scoring for military access is multiplied by this if it has an existing power cost relation
NDefines.NAI.DIPLOMATIC_ACTION_MILITARY_ACCESS_ENEMY_REGIMENTS_FACTOR = 20		-- AI scoring for military access is increased by this for each enemy regiment they are sheltering
NDefines.NAI.DIPLOMATIC_ACTION_VASSALIZE_DEVELOPMENT_FACTOR = 20				-- AI scoring for vassalize is increased by this for each development in target's provinces
NDefines.NAI.DIPLOMATIC_ACTION_ANNEX_DEVELOPMENT_FACTOR = 50					-- AI scoring for demand annexation is increased by this for each development in target's provinces
NDefines.NAI.DIPLOMATIC_ACTION_INTEGRATE_DEVELOPMENT_FACTOR = 50				-- AI scoring for integrate is increased by this for each development in target's provinces
NDefines.NAI.DIPLOMATIC_ACTION_EXCOMMUNICATE_ANTAGONIZE_FACTOR = 20				-- AI scoring for excommunicate is increased by this if they have an attitude with 'antagonize' desire
NDefines.NAI.DIPLOMATIC_ACTION_EXCOMMUNICATE_ANNEX_FACTOR = 20					-- AI scoring for excommunicate is increased by this if they have an attitude with 'annex' desire
NDefines.NAI.DIPLOMATIC_ACTION_EXCOMMUNICATE_NEIGHBOUR_FACTOR = 25				-- AI scoring for excommunicate is increased by this if they are neighbours
NDefines.NAI.DIPLOMATIC_ACTION_EXCOMMUNICATE_RIVAL_FACTOR = 35					-- AI scoring for excommunicate is increased by this if they are rivals
NDefines.NAI.DIPLOMATIC_ACTION_CRUSADE_DEVELOPMENT_FACTOR = 1					-- AI scoring for crusade is increased by this for each development in target's provinces
NDefines.NAI.DIPLOMATIC_ACTION_CRUSADE_ANTAGONIZE_FACTOR = 25					-- AI scoring for crusade is increased by this if they have an attitude with 'antagonize' desire
NDefines.NAI.DIPLOMATIC_ACTION_CRUSADE_ANNEX_FACTOR = 50						-- AI scoring for crusade is increased by this if they have an attitude with 'annex' desire
NDefines.NAI.DIPLOMATIC_ACTION_CRUSADE_NEIGHBOUR_FACTOR = 25					-- AI scoring for crusade is increased by this if they are neighbours
NDefines.NAI.DIPLOMATIC_ACTION_CRUSADE_RIVAL_FACTOR = 10						-- AI scoring for crusade is increased by this if they are rivals
NDefines.NAI.DIPLOMATIC_ACTION_CLAIM_THRONE_MAX_DEVELOPMENT_DIFFERENCE = 2		-- AI will not claim throne if target has more than their development * this value
NDefines.NAI.DIPLOMATIC_ACTION_CLAIM_THRONE_MIN_PRESTIGE_DIFFERENCE = 20		-- AI will not claim throne if they don't have at least this much more prestige
NDefines.NAI.DIPLOMATIC_ACTION_CLAIM_THRONE_MAX_DISTANCE = 100					-- AI will not claim throne if border distance is higher than this
NDefines.NAI.DIPLOMATIC_ACTION_CLAIM_THRONE_VASSALIZE_FACTOR = 100				-- AI scoring for claim throne is increased by this if they have an attitude with 'vassalize' desire
NDefines.NAI.DIPLOMATIC_ACTION_CLAIM_THRONE_DEVELOPMENT_FACTOR = 1				-- AI scoring for claim throne is increased by this for each development in target's provinces
NDefines.NAI.DIPLOMATIC_ACTION_CLAIM_THRONE_DEVELOPMENT_MAX = 100				-- Max amount of AI scoring for claim throne from province development
NDefines.NAI.DIPLOMATIC_ACTION_CLAIM_THRONE_OUR_CLAIMS_FACTOR = -50				-- AI scoring for claim throne is changed by this for each other throne they are claiming
NDefines.NAI.DIPLOMATIC_ACTION_CLAIM_THRONE_OTHER_CLAIMS_FACTOR = -25			-- AI scoring for claim throne is changed by this for each other country claiming the target's throne
NDefines.NAI.DIPLOMATIC_ACTION_GUARANTEE_PROTECT_FACTOR = 50					-- AI scoring for guarantee is changed by this if they have an attitude with the 'protect' desire
NDefines.NAI.DIPLOMATIC_ACTION_WARNING_MAX_DISTANCE = 50						-- AI will not warn if border distance is higher than this
NDefines.NAI.DIPLOMATIC_ACTION_WARNING_WARN_FACTOR = 50							-- AI scoring for warning is changed by this if they have an attitude with the 'warn' desire (multiplied by number of common neighbors )
NDefines.NAI.DIPLOMATIC_ACTION_INSULT_RELATIONS_THRESHOLD = 90					-- AI will only insult if relations are above this amount
NDefines.NAI.DIPLOMATIC_ACTION_INSULT_ANTAGONIZE_FACTOR = 50					-- AI scoring for insults is increased by this if they have an attitude with 'antagonize' desire
NDefines.NAI.DIPLOMATIC_ACTION_INSULT_ANNEX_FACTOR = 50							-- AI scoring for insults is increased by this if they have an attitude with 'annex' desire
NDefines.NAI.DIPLOMATIC_ACTION_INSULT_RIVAL_FACTOR = 10							-- AI scoring for insults is increased by this if they are rivals
NDefines.NAI.DIPLOMATIC_ACTION_INSULT_PREPARING_WAR_FACTOR = 200				-- AI scoring for insults is increased by this if it is preparing for war with them
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_BASE_FACTOR = 25					-- AI scoring for fabricating claims is always increased by this as long as the province is a conquest priority
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_STRATEGY_FACTOR = 0.5			-- AI scoring for fabricating claims based on strategic conquest priorities
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_OTHER_CB_FACTOR = 0				-- AI scoring for fabricating claims if they already have another CB usable on the province
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_NOT_ADJACENT_FACTOR = 0.5		-- AI scoring for fabricating claims if the province is not adjacent
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_HRE_FACTOR = 0.75				-- AI scoring for fabricating claims if both parts are HRE
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_HRE_EMPEROR_FACTOR = 0.5			-- AI scoring for fabricating claims if province is HRE and they are emperor (does not stack with the above penalty)
NDefines.NAI.DIPLOMATIC_ACTION_SOW_DISCONTENT_ANTAGONIZE_FACTOR = 25			-- AI scoring for sowing discontent is increased by this if they have an attitude with 'antagonize' desire
NDefines.NAI.DIPLOMATIC_ACTION_SOW_DISCONTENT_RIVAL_FACTOR = 25					-- AI scoring for sowing discontent is increased by this if they are rivals
NDefines.NAI.DIPLOMATIC_ACTION_AGITATE_FOR_LIBERTY_ANTAGONIZE_FACTOR = 25		-- AI scoring for agitating for liberty is increased by this if they have an attitude with 'antagonize' desire
NDefines.NAI.DIPLOMATIC_ACTION_AGITATE_FOR_LIBERTY_RIVAL_FACTOR = 25			-- AI scoring for agitating for liberty is increased by this if they are rivals
NDefines.NAI.DIPLOMATIC_ACTION_AGITATE_FOR_LIBERTY_DEVELOPMENT_FACTOR = 0.25	-- AI scoring for agitate for liberty multiplied by development of subject agitated.
NDefines.NAI.DIPLOMATIC_ACTION_AGITATE_FOR_LIBERTY_LD_FACTOR = 2				-- AI scoring for agitate for liberty multiplied by liberty desire percentage of subject agitated.
NDefines.NAI.DIPLOMATIC_ACTION_SABOTAGE_REPUTATION_ANTAGONIZE_FACTOR = 25		-- AI scoring for sabotage reputation is increased by this if they have an attitude with 'antagonize' desire
NDefines.NAI.DIPLOMATIC_ACTION_SABOTAGE_REPUTATION_RIVAL_FACTOR = 25			-- AI scoring for sabotage reputation is increased by this if they are rivals
NDefines.NAI.DIPLOMATIC_ACTION_STEAL_MAPS_ANTAGONIZE_FACTOR = 25				-- AI scoring for map stealing is increased by this if they have an attitude with 'antagonize' desire
NDefines.NAI.DIPLOMATIC_ACTION_STEAL_MAPS_REGION_RIVAL_VALUE_MULT = 0.25		-- AI scoring multiplier for map stealing is increased by this for region's value to rivals
NDefines.NAI.DIPLOMATIC_ACTION_STEAL_MAPS_REGION_SELF_VALUE_MULT = 0.5			-- AI scoring multiplier for map stealing is increased by this for region's value to self
NDefines.NAI.DIPLOMATIC_ACTION_SLANDER_MERCHANTS_ANTAGONIZE_FACTOR = 25			-- AI scoring for slander merchants is increased by this if they have an attitude with 'antagonize' desire
NDefines.NAI.DIPLOMATIC_ACTION_SLANDER_MERCHANTS_RIVAL_FACTOR = 25				-- AI scoring for slander merchants is increased by this if they are rivals
NDefines.NAI.DIPLOMATIC_ACTION_SABOTAGE_RECRUITMENT_ANTAGONIZE_FACTOR = 50		-- AI scoring for sabotage recruitment is increased by this if they have an attitude with 'antagonize' desire
NDefines.NAI.DIPLOMATIC_ACTION_SABOTAGE_RECRUITMENT_RIVAL_FACTOR = 50			-- AI scoring for sabotage recruitment is increased by this if they are rivals
NDefines.NAI.DIPLOMATIC_ACTION_CORRUPT_OFFICIALS_ANTAGONIZE_FACTOR = 25			-- AI scoring for slander merchants is increased by this if they have an attitude with 'antagonize' desire
NDefines.NAI.DIPLOMATIC_ACTION_CORRUPT_OFFICIALS_RIVAL_FACTOR = 25				-- AI scoring for corrupt officials is increased by this if they are rivals
NDefines.NAI.DIPLOMATIC_ACTION_COALITION_DISTANCE_FACTOR = 100					-- AI scoring for joining/forming coalition based on distance
NDefines.NAI.DIPLOMATIC_ACTION_COALITION_THREAT_FACTOR = 0.5					-- AI scoring for joining/forming coalition based on threat score
NDefines.NAI.DIPLOMATIC_ACTION_COALITION_RELATIONS_FACTOR = 0.5					-- AI scoring for joining/forming coalition based on negative relations
NDefines.NAI.DIPLOMATIC_ACTION_COALITION_SIZE_FACTOR = 1						-- AI scoring for joining/forming coalition based on number of cities
NDefines.NAI.DIPLOMATIC_ACTION_COALITION_SIZE_FACTOR_MAX = 50					-- Size factor will not go above this regardless of number of cities
NDefines.NAI.DIPLOMATIC_ACTION_ENFORCE_PEACE_FORCE_BALANCE_MULT = 1				-- AI scoring for enforce peace is multiplied by this.
NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_WAR_WITH_RIVAL_FACTOR = 30				-- AI scoring for giving subsidies to a country that is at war with its rival
NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_RELATIVE_INCOME_FACTOR = 30			-- AI scoring for giving subsidies to a country based on its relative income to the AI nation (lower income = higher scoring)
NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_RELATIONS_FACTOR = 0.5					-- AI scoring for giving subsidies to a country based on opinion of the other country
NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_RELATIONS_MAX = 100					-- Relations above this will not be considered for DIPLOMATIC_ACTION_SUBSIDIES_RELATIONS_FACTOR
NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_MAX_OCCUPIED = 0.5						-- Max fraction of a country that can be occupied/besieged for AI to consider it worth giving subsidies
NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_MAX_RELATIVE_INCOME = 0.33				-- Max relative montly income that a country can have for the AI to consider it in need of subsidies
NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_PREVIOUS_SUBSIDIES_FACTOR = -100		-- AI scoring for giving subsidies based on previous subsidies nation is receiving relative to income
NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_INDEBTED_FACTOR = 20					-- AI scoring for giving subsidies to an ally in heavy debt
NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_MIN_VALUE = 0.5						-- Minimum amount of subsidies that AI considers worthwhile
NDefines.NAI.DIPLOMATIC_ACTION_TRADE_POWER_ACCEPTANCE_MULT = 3					-- AI scoring for transfer trade power based on willingness to accept it if offered to them
NDefines.NAI.DIPLOMATIC_ACTION_STEER_TRADE_ACCEPTANCE_MULT = 3					-- AI scoring to retain trade steering based on willingness to accept it if offered to them
NDefines.NAI.DIPLOMATIC_ACTION_TRADE_POWER_TRADE_INTEREST_FACTOR = 25			-- AI scoring for transfer trade power is increased by this if they have trade interest
NDefines.NAI.DIPLOMATIC_ACTION_TRADE_POWER_THRESHOLD = 1						-- AI will not ask to transfer trade power unless value of shared nodes is at least this high
NDefines.NAI.DIPLOMATIC_ACTION_TRADE_POWER_FACTOR = 25							-- AI scoring for transfer trade power is increased by this for each 1.0 value in shared nodes
NDefines.NAI.DIPLOMATIC_ACTION_TRADE_POWER_ALLIANCE_FACTOR = 0.25				-- AI threshold for transfer trade power will be mulitplied by this if the two countries have an alliance
NDefines.NAI.DIPLOMATIC_ACTION_SUPPORT_HEIR_DEVELOPMENT_FACTOR = 2				-- AI scoring for support heir is increased by this for each development in target's provinces
NDefines.NAI.DIPLOMATIC_ACTION_SUPPORT_HEIR_ALLIANCE_FACTOR = 2					-- AI scoring for support heir is multiplied by this if the two countries have an alliance
NDefines.NAI.DIPLOMATIC_ACTION_BUILD_SPY_NETWORK_RIVAL_FACTOR = 50				-- AI scoring to build spy network in neighboring rivals, or overlord if disloyal subject.
NDefines.NAI.AI_WANT_ACCEPT_CULTURES = 100										-- How much the AI values having much development in accepted cultures.
NDefines.NAI.DIPLOMATIC_ACTION_INFILTRATE_BASE_FACTOR = 25						-- AI infiltrate administration base scoring
NDefines.NAI.DIPLOMATIC_ACTION_INFILTRATE_POWER_FACTOR = 5						-- AI base scoring for infiltrate administration is multiplied by at most this proportion of relative military strength
NDefines.NAI.DIPLOMATIC_ACTION_INFILTRATE_RIVAL_FACTOR = 25						-- AI scoring for infiltrate administration is increased by this if they are rivals
NDefines.NAI.DIPLOMATIC_ACTION_COUNTER_ESPIONAGE_SPY_PROPENSITY_FACTOR = 0.4	-- AI scoring for counter espionage depending on how many spy network points they spent in recent years.
NDefines.NAI.DIPLOMATIC_ACTION_COUNTER_ESPIONAGE_ENEMY_FACTOR = 25				-- AI scoring for counter espionage against an active enemy (someone we're at war with, antagonize or otherwise rival).
NDefines.NAI.DIPLOMATIC_ACTION_TRIBUTARY_ACCEPTANCE_PER_DEVELOPMENT = -0.5		-- AI scoring for accepting becoming a tributary state per raw development
NDefines.NAI.DIPLOMATIC_ACTION_TRIBUTARY_EMPIRE_FACTOR = 10						-- AI scoring for establishing Tributary States is increased by this if actor is Celestial Emperor or has horde government with rank Empire.
NDefines.NAI.ALLIANCE_DESIRE_TOO_MANY_RELATIONS = -20							-- AI desire/acceptance for alliance when it has or will get too many relations. Multiplies with number of relations above limit.
NDefines.NAI.SUPPORT_INDEPENDENCE_DESIRE_TOO_MANY_RELATIONS = -20				-- AI desire/acceptance for supporting independence when it has or will get too many relations. Multiplies with number of relations above limit.
NDefines.NAI.MARRIAGE_DESIRE_TOO_MANY_RELATIONS = -50							-- AI desire/acceptance for royal marriange when it has or will get too many relations. Multiplies with number of relations above limit.
NDefines.NAI.GUARANTEE_DESIRE_TOO_MANY_RELATIONS = -50							-- AI desire for guaranteeing when it has or will get too many relations. Multiplies with number of relations above limit.

NDefines.NAI.INVADING_BRAVERY = 1												-- If (defender strength) / (invader strength) > INVADING_BRAVERY, the AI won't attempt a naval invasion.
NDefines.NAI.INVADING_MAX_AWAY_RATIO = 1										-- AI will never send more than this ratio to invade (measured in strength).
																				-- Rosth: was 0.5 in 2.52.06. Changed to 1 under the assumption that if the AI can launch a naval invasion it has naval superiority to begin with and there is no reason to not use as many troops as possible.
NDefines.NAI.HOME_FLEET_MAX_RATIO = 0.85										-- Maximum proportion of warships in home fleet.
NDefines.NAI.TRADE_POLICY_PROPAGATE_RELIGION_SCORE = 50							-- Score for propagate religion trade policy (if selectable)
NDefines.NAI.TRADE_POLICY_PREPARING_FOR_WAR_PER_PROVINCE_SCORE = 6				-- Score per enemy province while preparing war for attack bonus trade policy (if selectable)
NDefines.NAI.TRADE_POLICY_AT_WAR_PER_PROVINCE_SCORE = 5.5						-- Score per enemy province while preparing war for attack bonus trade policy (if selectable)
NDefines.NAI.TRADE_POLICY_MAXIMIZE_PROFITS_SCORE = 15							-- Score for maximize profit trade policy
NDefines.NAI.TRADE_POLICY_IMPROVE_RELATIONS_PER_COUNTRY_SCORE = 5				-- Score per country with merchant for improve relations policy
NDefines.NAI.TRADE_POLICY_SPY_OFFENCE_PER_COUNTRY_SCORE = 5						-- Score per country with merchant for spy offence policy
NDefines.NAI.DRILL_BONUS_WAR_READINESS = 0.08									-- Bonus for war readiness of drilled units
NDefines.NAI.MONTHS_STOP_DRILLING_BEFORE_WAR = 5								-- Months before a prepared war to stop drilling.
																				-- Rosth: in early patches the AI garthered troops on a border with a country it wanted to declare on, but that doesn't seem to be the case anymore (at least not in 1.29). Still, extra 2 months to regain morale wouldn't hurt (and also if they do somehow decide to preemptively move their armies - all the better).
NDefines.NAI.DRILLING_BUDGET_OF_SURPLUS = 0.75									-- Max amount of surplus to be used for drilling
NDefines.NAI.DRILLING_DEBT_SURPLUS_RATIO_THRESHOLD = 0.025						-- AI will only consider drilling if Surplus / Debt ratio is above
NDefines.NAI.DRILLING_ACCEPTABLE_THREAT_REDUCTION = 100							-- Acceptable threat reduction for drilling
NDefines.NAI.DANGEROUS_ESTATE_INFLUENCE_BUFFER = 100							-- AI will assign estates up to ESTATE_DANGER_THRESHOLD minus this (See ai_territory_modifier)
NDefines.NAI.ADVISOR_MIN_SKILL_RELUCTANT_FIRE = 3								-- AI will be reuluctant to fire advisors with skill above this (due to prior investment)
NDefines.NAI.ADVISOR_PROMOTION_AGE_CUTOFF = 40									-- AI will not promote advisors above this age
NDefines.NAI.MIN_FORCE_LIMIT_SHARE_REGION_ASSIGN = 0.1							-- AI will only assign armies larger that this to a region
NDefines.NAI.MAX_ARMIES_NEW_REGION_ASSIGN_ALGORITHM = 24						-- Max. amount of armies to use in new region assignment algorithm (fall back to old one).
																				-- Rosth: this value determines the maximum desired number of AI in a given region. "Region" refers to AI regions visible if you type "mapmode airegion" in the console. Based on what has been said in ACCEPTABLE_BALANCE_DEFAULT about the fact that the evaluation score heavily favors big stacks, lowering this would make the AI "doomstack" more but also potentially suffer more attrition. Vanilla value is 12.
NDefines.NAI.MAX_TASKS_NEW_REGION_ASSIGN_ALGORITHM = 200						-- Max. amount of tasks to use in new region assignment algorithm (fall back to old one).
																				-- Rosth: higher value means more frequent reassessment of AI stack movement orders. "Region" refers to AI regions visible if you type "mapmode airegion" in the console. Vanilla value is 100. This would in all likelihood not affect AI behaviour as it would be hard for the AI to issue all of these tasks all at the same time.
NDefines.NAI.ELECTORAL_REFORMATION_CONVERT_TRESHOLD = 0.1						-- How much of an electors development needs to be a reformed religion for it to try and reform
NDefines.NAI.TRADE_COMPANY_INVESTMENT_COST_THRESHOLD = 1						-- How many times the cost of the investment must be in the treasury to consider buying it
NDefines.NAI.ASSIMILATION_INTEREST_AMOUNT_FACTOR = 50							-- Influence on assimilation interest from number of provinces left to conquer.
																				-- Rosth: as the AI cannot pick any other colonial policy other than native coexistence, I am assuming it doesn't refer to the native trading policy and instead refers to consolidation of cultures/culture groups. At worst it does nothing, at best it would make the AI more interested in conquering land that has the same culture to its own.
NDefines.NAI.INVASION_ARMY_LOOKUP_INTERVAL_ON_FAILURE = 5						-- If AI fails to find an army for an invasion it will try again in this number of days
NDefines.NAI.CHARTER_COMPANY_BASE_RELUCTANCE = 10000							-- Base reluctance to giving away provinces in charter company diplo action
NDefines.NAI.CHARTER_COMPANY_DEVELOPMENT_RELUCTANCE = 0							-- How much development needed to add one reluctance
NDefines.NAI.WAR_WARSCORE_TO_JOIN = -100										-- Minimum warscore for the AI to join a call for arms
NDefines.NAI.WAR_MIN_WARSCORE_TO_JOIN = -25										-- Starting warscore for the AI to join a call for arms
NDefines.NAI.ARMY_DISTANCE_SCORE_IMPACT = 0.625 								-- Army <-> province distance impact on province evaluation.
																				-- Rosth: makes the AI less likely to run around like a moron. Inverse of this number (1/x) is multiplied by the distance value, which can be seen by selecting an AI stack, typing "mapmode aieval" in the console and hovering over a province. The lower the evaluation score for a province, the higher the AI's stack desire to move to it (applies to teal-colored provinces). This means that lowering this define would make the distance score value higher, which in turn would make that stack prioritise provinces that are closer to it over the ones that are further away. Vanilla value is 0.5.
NDefines.NAI.BORDER_DISTANCE_SCORE_IMPACT = 2.5 								-- Border <-> province distance impact on province evaluation.
																				-- Rosth: same principle as described above, only here the distance value is multiplied directly by this number. The further the province is from the AI's border, the less desireable it is. Vanilla value is 3.
NDefines.NAI.IMPORANT_PROVINCE_THRESHOLD = 0.015 								-- AI will try to defend provinces under threat worth more than this percentage of total development. Vanilla value is 0.05.
NDefines.NAI.REGION_PLANNING_HOMELAND_PRIORIZATION = 3							-- Homeland priorization when assigning armies to regions (only applied when actually threatened). Vanilla value is 3.5
																				-- Rosth: I'm assuming "homeland" either means "non-overseas provinces" or AI region that has it's capital.
NDefines.NAI.MISSIONARY_MAINTENANCE_SHARE = 0.2									-- The most an AI will spend of its income on a missionary
